language: dart

dart: [dev, 2.8.0-dev.0.0, 2.8.0-dev.1.0, 2.8.0-dev.2.0]

before_script: ./tool/travis_before_script.sh
dart_task:
  - test test/firestore_test.dart

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
