language: dart

dart:
  - stable

before_script: ./tool/travis_before_script.sh

dart_task:
  - test: --platform vm
  - test: --platform firefox
  - test: --platform dartium
    install_dartium: true
  - dartanalyzer
  - dartfmt

cache:
  directories:
    - $HOME/.pub-cache
