language: dart


stages:
  - analyze_and_format
  - name: test
    if: (type != pull_request) OR (sender = kevmoo)

jobs:
  include:
    - dart: dev
      dart_task: dartanalyzer
    - dart_task: dartfmt
      dart: dev

    - stage: test
      dart: [dev, 2.8.0-dev.0.0, 2.8.0-dev.1.0, 2.8.0-dev.2.0]
      before_script: ./tool/travis_before_script.sh
      dart_task: test test/firestore_test.dart

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
