language: dart

dart:
  - stable
  - dev

before_script: ./tool/travis_before_script.sh

dart_task:
  - test: --platform vm
  - test: --platform firefox
  - dartanalyzer
  - dartfmt

matrix:
  include:
    - dart: stable
      dart_task: test
      test: --platform dartium
      install_dartium: true

cache:
  directories:
    - $HOME/.pub-cache
