# Created with package:mono_repo v2.5.0-dev
language: dart

# Custom configuration
branches:
  only:
    - master

jobs:
  include:
    - stage: work
      name: "SDK: dev; PKGS: firebase, shared_assets; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings --fatal-infos .`]"
      dart: dev
      os: linux
      env: PKGS="firebase shared_assets"
      script: tool/travis.sh dartfmt dartanalyzer
    - stage: work
      name: "SDK: dev; PKG: firebase; TASKS: `../tool/travis_before_script.sh && pub run test`"
      dart: dev
      os: linux
      env: PKGS="firebase"
      script: tool/travis.sh command

stages:
  - work

cache:
  directories:
    - "$HOME/.pub-cache"
    - firebase/.dart_tool/build
    - shared_assets/.dart_tool/build
