language: dart

stages:
  - analyze_and_format
  - name: test
    if: (type != pull_request) OR (sender = kevmoo)

# Pinning to 2.0.0-dev.63 until the latest dev release is fixed
jobs:
  include:
    - dart: 2.0.0-dev.63.0
      dart_task: dartanalyzer

    - dart: 2.0.0-dev.63.0
      dart_task: dartfmt

    - stage: test
      dart: 2.0.0-dev.63.0
      before_script: ./tool/travis_before_script.sh
      dart_task: test # default to vm and chrome

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
