name: firebase
description: Firebase libraries for Dart on the web and server
version: 5.0.2-dev
authors:
- Jana Moudra <jana.moudra@gmail.com>
- Kevin Moore <kevmoo@google.com>
homepage: https://github.com/firebase/firebase-dart

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:
  http: ^0.11.3
  js: ^0.6.0

dev_dependencies:
  googleapis_auth: ^0.2.3+5
  path: ^1.3.9
  test: ^1.0.0
  service_worker: ^0.2.0

  build_runner: ^0.10.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
