name: firebase
description: Dart libraries for Firebase
version: 4.4.0-dev
authors:
- Jana Moudra <jana.moudra@gmail.com>
- Kevin Moore <kevmoo@google.com>
homepage: https://github.com/firebase/firebase-dart

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  browser: '^0.10.0'
  func: ">=0.1.0 <2.0.0"
  http: '^0.11.3'
  js: "^0.6.0"

dev_dependencies:
  googleapis_auth: '^0.2.3+5'
  path: '^1.3.9'
  test: '^0.12.17'
