# See https://pub.dev/packages/mono_repo for details on this file
dart:
- dev

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos .

cache:
  directories:
  - .dart_tool/build
