# See https://pub.dev/packages/mono_repo for details on this file
dart:
- 2.7.0
- dev

stages:
- analyze_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
- unit_test:
  - command: pub run build_runner build example --fail-on-severe --delete-conflicting-outputs
  - command:
    - pushd ../_shared_assets
    - pub get
    - dart create_config.dart
    - popd
    - pub run test

cache:
  directories:
  - .dart_tool/build
