# Created with package:mono_repo v3.4.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
  CONFIG_DATA: "${{ secrets.CONFIG_DATA }}"
  SERVICE_ACCOUNT_JSON: "${{ secrets.SERVICE_ACCOUNT_JSON }}"

jobs:
  job_004:
    name: "work; PKG: firebase; `pushd ../_shared_assets && pub get && dart create_config.dart && popd && pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase;commands:command_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: dart --version
      - uses: actions/checkout@v2
      - id: firebase_pub_upgrade
        name: "firebase; pub upgrade --no-precompile"
        working-directory: firebase
        run: pub upgrade --no-precompile
      - if: "steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: |
          pushd ../_shared_assets
          pub get
          dart create_config.dart
          echo 'looking at config'
          cat lib/config.json
          echo 'looking at service account'
          cat lib/service_account.json
          popd
