# Created with package:mono_repo v5.0.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
  CONFIG_DATA: "${{ secrets.CONFIG_DATA }}"
  SERVICE_ACCOUNT_JSON: "${{ secrets.SERVICE_ACCOUNT_JSON }}"

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; Dart dev; PKGS: _shared_assets, firebase; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:_shared_assets-firebase;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:_shared_assets-firebase
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: _shared_assets_pub_upgrade
        name: _shared_assets; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: _shared_assets
        run: dart pub upgrade
      - name: "_shared_assets; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps._shared_assets_pub_upgrade.conclusion == 'success'"
        working-directory: _shared_assets
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "_shared_assets; dart analyze --fatal-infos ."
        if: "always() && steps._shared_assets_pub_upgrade.conclusion == 'success'"
        working-directory: _shared_assets
        run: dart analyze --fatal-infos .
      - id: firebase_pub_upgrade
        name: firebase; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: firebase
        run: dart pub upgrade
      - name: "firebase; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "firebase; dart analyze --fatal-infos ."
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: dart analyze --fatal-infos .
  job_003:
    name: "unit_test; Dart 2.12.0; PKG: firebase; `dart run build_runner build example --fail-on-severe --delete-conflicting-outputs`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:firebase;commands:command_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:firebase
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: firebase_pub_upgrade
        name: firebase; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: firebase
        run: dart pub upgrade
      - name: "firebase; dart run build_runner build example --fail-on-severe --delete-conflicting-outputs"
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: dart run build_runner build example --fail-on-severe --delete-conflicting-outputs
    needs:
      - job_001
      - job_002
  job_004:
    name: "unit_test; Dart 2.12.0; PKG: firebase; `pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:firebase;commands:command_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:firebase
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: firebase_pub_upgrade
        name: firebase; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: firebase
        run: dart pub upgrade
      - name: "firebase; pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test"
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: "pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test"
    needs:
      - job_001
      - job_002
  job_005:
    name: "unit_test; Dart dev; PKG: firebase; `dart run build_runner build example --fail-on-severe --delete-conflicting-outputs`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase;commands:command_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: firebase_pub_upgrade
        name: firebase; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: firebase
        run: dart pub upgrade
      - name: "firebase; dart run build_runner build example --fail-on-severe --delete-conflicting-outputs"
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: dart run build_runner build example --fail-on-severe --delete-conflicting-outputs
    needs:
      - job_001
      - job_002
  job_006:
    name: "unit_test; Dart dev; PKG: firebase; `pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase;commands:command_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:firebase
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: firebase_pub_upgrade
        name: firebase; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: firebase
        run: dart pub upgrade
      - name: "firebase; pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test"
        if: "always() && steps.firebase_pub_upgrade.conclusion == 'success'"
        working-directory: firebase
        run: "pushd ../_shared_assets && dart pub get && dart create_config.dart && popd && dart test"
    needs:
      - job_001
      - job_002
  job_007:
    name: Notify failure
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' || github.event_name == 'schedule') && failure()"
    steps:
      - run: |
          curl -H "Content-Type: application/json" -X POST -d \
            "{'text':'Build failed! ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'}" \
            "${CHAT_WEBHOOK_URL}"
        env:
          CHAT_WEBHOOK_URL: "${{ secrets.CHAT_WEBHOOK_URL }}"
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
      - job_005
      - job_006
